### PR TITLE
fix flag broadcast xp msgs

### PR DESCRIPTION
**Pull request by fokkonaut**

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Everything in C except ``NULL`` ``false`` and ``0`` is truthy so you could use the int as the bool as well to improve readability because less variables less confusion.

**Comment by fokkonaut** [comment]
did it also like that in the money tile broadcasts

**Comment by ChillerDragon** [comment]
Then you can improve that code as well :p probably written by a nobo called zillydreckhuhn

**Comment by fokkonaut** [comment]
no, written by me because you did it really crappy. just merge it, its good like that

**Pull request merged**
