### PR TITLE
Save timeout code

### PR DESCRIPTION
**Pull request by ChillerDragon**
Can be used for some autologin stuff or to validate if persons own the acc if they lost the password.

### CODE REVIEW

**Comment by fokkonaut** [comment]
lol you mark it as sensitive data on ddnet and here you want to even save it? xd

**Comment by fokkonaut** [comment]
and i thought we have to wait until we fixed the login/logout lag

**Comment by ChillerDragon** [comment]
@fokkonaut 

> lol you mark it as sensitive data on ddnet and here you want to even save it? xd

I wanted to censor it on ddnet to save it in ddnet++ and use it more effective heueueu. Because if the timeout codes get more hidden we could use them more as account verfication. At first i thought they could maybe used for autologin but I think that would be too much of a security risk. But saving them to have at least something for account verfication would be nice. If for example someone forgets the password it is hard to tell if the player is the real owner of the account. Even the ips don't help because they change. So if the timeout code is there in addition this could be helpful in some cases. But this needs another command in addition that compares the current online player timeout code with the account timeout code.

> and i thought we have to wait until we fixed the login/logout lag

That is why I made it a pr because I was not sure if it really affects the performance. I thought that only the login causes problems and since the timeout code is not loaded from the database on login and only saved at logout I hoped it could be okay.

**Comment by fokkonaut** [comment]
logouts also lag

**Comment by ChillerDragon** [comment]
Okay I guess no merge then until we improved the account system performance.

**Comment by ChillerDragon** [comment]
closed due to conflicts

**Pull request closed without merging**
