### PR TITLE
blmapchill update to v0109, opened cinema, fixed hookthrough + fixed bot for it

### PR DESCRIPTION
**Pull request by fokkonaut**

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Sorri for rejecting it agian but please keep these things in mind:

- map commits only include map changes nothing else so two binary files changes / renamed
- follow this naming convention for map commits also care for lower/upper case:
``Update to BlmapChill v0109 (opened cinema, fixed hookthrough + fixed bot for it)``
( renaming the pr doesnt help it is the commit message that matters )
- For personal settings changes like switching the map please use from now on the local.cfg
- The nobo spawn off is a good idea but has to be a different commit
- Also if the character code is related to the map change put it in another commit please

**Comment by fokkonaut** [comment]
fuck you i dont do anything anymore for you

**Comment by fokkonaut** [comment]
das ist so behindert junge hab mal verständnis das deine "regeln" einfach kompletter bullshit sind

**Comment by fokkonaut** [comment]
wen juckt dieser dreck eigentlich?

**Pull request closed without merging**
